### ISSUE TITLE
Error en upload

### ISSUE THREAD

**Issue by scriptArchitect** [digaresc/revisamigrieta-api-backend#16]
Intenté subir una imagen con estos 3 endpoints

https://revisamigrieta.appspot.com/_ah/api/upload
https://revisamigrieta.appspot.com/_ah/api/v1/upload
https://revisamigrieta.appspot.com/_ah/api/v1/grietas/upload

Con los 3 me marca el mismo error

<HTML>
<HEAD>
<TITLE>Bad Request</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Bad Request</H1>
<H2>Error 400</H2>
</BODY>
</HTML>

**Comment by digaresc** [comment]
Ya quedo funcionando, se cambio el README y se agrego ejemplo.
